### ISSUE TITLE
MultiPlotFrame example

### ISSUE THREAD

**Issue by manirm** [newville/wxmplot#31] opened 2017-04-08 01:29 UTC
Trying to run MultiPlotFrame example.  Getting the following error message....
Python version: 3.5.3; wxPython version: 3.0.3.dev2891+36b8076 msw (phoenix)
~~~~
AttributeError                            Traceback (most recent call last)
<ipython-input-1-9c35c2132dbc> in <module>()
     10 app = wx.App()
     11 
---> 12 pframe = wxmplot.MultiPlotFrame(rows=2,cols=3,panelsize=(2.5,1.75))
     13 
     14 

C:\apps\python35\lib\site-packages\wxmplot\multiframe.py in __init__(self, parent, rows, cols, framesize, panelsize, **kws)
     28         self.panelsize = panelsize
     29         self.current_panel = (0,0)
---> 30         self.BuildFrame()
     31 
     32     def set_panel(self,ix,iy):

C:\apps\python35\lib\site-packages\wxmplot\multiframe.py in BuildFrame(self)
    111         self.SetStatusText('',0)
    112 
--> 113         self.BuildMenu()
    114         sizer = wx.GridBagSizer(self.rows,self.cols)
    115 

C:\apps\python35\lib\site-packages\wxmplot\baseframe.py in BuildMenu(self)
    192         MenuItem(self, mopts, "Configure Plot\tCtrl+K",
    193                  "Configure Plot styles, colors, labels, etc",
--> 194                  self.panel.configure)
    195         MenuItem(self, mopts, "Toggle Legend\tCtrl+L",
    196                  "Toggle Legend Display",

AttributeError: 'NoneType' object has no attribute 'configure'
~~~~

**Comment by newville** [comment] 2017-04-08 04:14
@manirm sorry for the trouble. I can reproduce this and am not sure how it ever worked.  It looks like MultiPlotFrame needs its own MenuBar....  Will investigate....

**Comment by newville** [comment] 2017-04-09 16:12
@manirm this is now be fixed in github master branch.

**Closed by newville** 2017-04-09 16:12 UTC
